### ISSUE TITLE
Valid password not accepted

### ISSUE THREAD

**Issue by BWibo** [keitaroinc/ckanext-password-policy#6]
As shown in the example below, some password, that should be accepted are not.

```text
Password       Accepted
testTEST123!   yes
=testTest12!   yes
=1234A@bde34   no
=1234A$bde34   yes
```

### Settings
```text
ckanext.password_policy.failed_logins = '3'
ckanext.password_policy.password_length = '12'
ckanext.password_policy.user_locked_time = '600'
```

### Versions
- CKAN `2.9.9`, Docker Keitaro Debian image
- `ckanext-password-policy`: https://github.com/keitaroinc/ckanext-password-policy/commit/5618dc9ed433afa891e6194c9445b36bba0f5b10, latest commit to `montreal` branch. `master` is not working.

**Comment by BWibo** [comment]
Look's like the letter "@" is missing here: https://github.com/keitaroinc/ckanext-password-policy/blob/8626e2045933c583304607722faefdb5148cd91c/ckanext/password_policy/helpers.py#L55

**Comment by blagojabozinovski** [comment]
> Look's like the letter "@" is missing here:
> 
> https://github.com/keitaroinc/ckanext-password-policy/blob/8626e2045933c583304607722faefdb5148cd91c/ckanext/password_policy/helpers.py#L55

Looks like that's the issue. If You want You can make PR.
