### ISSUE TITLE
CKAN 2.10.

### ISSUE THREAD

**Issue by MarijaKnezevic** [keitaroinc/ckanext-password-policy#7]
Hi,
since it is not listed under requirements, I assume that the plugin is not tested for CKAN 2.10. Is there a plan to migrate the plugin to CKAN 2.10?
When using it with CKAN 2.10 it gives an error `No module named 'ckan.lib.repoze_plugins' `
Thank you very much 👍

**Comment by blagojabozinovski** [comment]
@MarijaKnezevic CKAN 2.10 doesn't use the FriendlyFormPlugin, so that part needs to be completly rewriten. So far no date to migrate the plugin to 2.10, but hope it will be soon.
